### Get all products
GET http://localhost:5103/api/product
Accept: application/json

###

### Search products
GET http://localhost:5103/api/product?search=lap
Accept: application/json

###

### Sort by price
GET http://localhost:5103/api/product?sortBy=price
Accept: application/json

###

### Pagination
GET http://localhost:5103/api/product?skip=0&take=5
Accept: application/json

###

### Get by ID
GET http://localhost:5103/api/product/1
Accept: application/json

###

### Create
POST http://localhost:5103/api/product
Content-Type: application/json

{
  "name": "Tablet",
  "price": 450
}

###

### Update
PUT http://localhost:5103/api/product/1
Content-Type: application/json

{
  "name": "Laptop Pro",
  "price": 1500
}

###

### Delete
DELETE http://localhost:5103/api/product/2
