### Health check
GET http://localhost:5103/health
Accept: application/json


### Get all products (with pagination metadata)
GET http://localhost:5103/api/product
Accept: application/json

###

### Search products by name
GET http://localhost:5103/api/product?search=lap
Accept: application/json

###

### Get available product categories
GET http://localhost:5103/api/product/categories
Accept: application/json

###


### Filter by category
GET http://localhost:5103/api/product?category=Electronics
Accept: application/json

###

### Filter by price range
GET http://localhost:5103/api/product?minPrice=100&maxPrice=1000
Accept: application/json

###

### Sort by price
GET http://localhost:5103/api/product?sortBy=price
Accept: application/json

###

### Pagination (skip/take)
GET http://localhost:5103/api/product?skip=0&take=2
Accept: application/json

###

### Get product by ID
GET http://localhost:5103/api/product/1
Accept: application/json

###

### Create product
POST http://localhost:5103/api/product
Content-Type: application/json

{
  "name": "headphones beatsr",
  "price": 250,
  "category": "audio"
}

###

### Update product
PUT http://localhost:5103/api/product/1
Content-Type: application/json

{
  "name": "Laptop Pro Max",
  "price": 1800,
  "category": "Electronics"
}

###

### Soft delete product
DELETE http://localhost:5103/api/product/2
Accept: application/json

###

### Verify deleted product is not returned
GET http://localhost:5103/api/product/2
Accept: application/json

### Trigger unhandled exception (invalid route / edge case)
GET http://localhost:5103/api/product/999999999999
Accept: application/json
