### Get all products
GET http://localhost:5103/api/product
Accept: application/json

###

### Get product by ID
GET http://localhost:5103/api/product/1
Accept: application/json

###

### Add a new product
POST http://localhost:5103/api/product
Content-Type: application/json

{
    "name": "Tablet",
    "price": 450
}

###

### Update a product
PUT http://localhost:5103/api/product/1
Content-Type: application/json

{
    "id": 1,
    "name": "Laptop Pro",
    "price": 1500
}

###

### Delete a product
DELETE http://localhost:5103/api/product/2
